# Generated by Django 4.2.1 on 2023-07-20 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('img', models.FileField(null=True, upload_to='static', verbose_name='Kategori Resmi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün adı')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.FileField(upload_to='product', verbose_name='Ürün Resmi')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('stok', models.IntegerField(verbose_name='Stok')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Fiyat')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı - Satıcı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
